config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "projects#index"
  get '', to: 'projects#index'
  get '/index', to: 'projects#index'
  
  patch '/create', to: 'projects#create'
  post '/create', to: 'projects#create'

  patch '/update/:id', to: 'projects#update'

  resources :awe
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :todos
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :project
  validates :text, presence: true,  on: :create
  validates :text, length: { minimum: 2 }, on: :create
  validates :text, length: { maximum: 60 }, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects = Project.includes(:todos).order(:id)
	end

	def create	
		Todo.create(text: todo_params[:text], project: Project.find(todo_params[:project_id]))
		redirect_to :root
	end

	def update
		todo = Todo.find(params[:id])
		todo.is_completed = !todo.is_completed
		todo.save
		
		respond_to do |format|
	     format.json { render json: @todo, :status => :ok}
	    end
	end

	private def todo_params
		params.require(:todo).permit(:text, :project_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OblokoGroup</title>
    <%= csrf_meta_tags %>
    <meta content="width=device-width" name="viewport">
    <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>  
  </head>
  <body>
    <%=yield %>
  </body>
</html>

app/views/projects/index.html.erb
<div id="divHead">
	<h1>Задачи</h1>
	<a href='#'  id='show-add-form'>
		<img src='<%=image_path("addTodoIcon.png")%>' alt='add Todo' />
	</a>
</div>

<div class='container'>
<div id='todo-list-area' class='row'>
<% @projects.each do |project| %>
<div class='col-md-4 col-lg-4 col-sm-4'>
<div class="panel panel-default">
	<div class="panel-header"><h4><%= project.title %></h4></div>
  <div class="panel-body">
	<% project.todos.each do |todo| %>
	<ul class='todo-list'>
		<li>
		 <input type="checkbox" name='todo[is_completed_<%=todo.id %>]' id="todo[is_completed_<%=todo.id %>]" data-id='<%=todo.id %>' <%='checked' if todo.is_completed %> />
	     <label class='<%='crossOfList' if todo.is_completed %>' for="todo[is_completed_<%=todo.id %>]"><%= todo.text %></label>	
		</li>
	</ul>
	<% end %>
  </div>
</div>
</div>
<% end %> 
</div>
</div>

<div id='form-add-todos' class="modalDialog">
	<div>
	<div class="title-todo-odd-form">
		НОВАЯ ЗАДАЧА
	</div>
	<%= form_with model: @todo, url: create_path  do |form| %>
	 <%= fields :todo do |fields| %>
	<div class="field-title-add-todo-form">
		<%= fields.text_field :text, {:placeholder => 'Название задачи...'} %>
	</div>
	<% end %>
	<% cities_array = @projects.map { |city| [city.title, city.id] } %>
	<div class="select-add-todo-form">
		<select class="js-example-disabled-results" name="todo[project_id]" id="todo_project_id">
	   	 <%= options_for_select(cities_array) %>
	 	</select>
	</div>
	<div class="submit-button-add-todo-form">
	 <%= submit_tag("Отмена", { :name => 'reset', :id => 'reset_button', :type => "reset", :class => 'btn btn-secondary' }) %> 
	 <%= submit_tag("Ок", { :name => 'submit', :id => 'submit_button', :type => "submit", :class => 'btn btn-primary' }) %>
	</div>
	<% end %>

	</div>
</div>